.gitattributes
Assets/Editor/TurnOffGpuEmulation.cs
Assets/ThirdParty/SteamVR/Resources/SteamVR_Settings.asset

Fix some warnings and dev workflow things I ran across while looking into the .glb issue

Small quality-of-life things

---

README.md

* OCULUS_SUPPORTED was added automatically in 00fb5e958942797fbfa4a813d025391fd26fc8c6
* Build paths are relative to the parent of the source tree

Update README with Q2 tweaks

---

.gitignore
README.md

Suggest using Oculus Unity Package 23.1

---

Assets/PlatformConfigPC.asset
Assets/Scripts/Rendering/UsdPathSerializer.cs
ProjectSettings/ProjectSettings.asset
Support/ThirdParty/ffmpeg/licenses/ffmpeg_COPYING
Support/ThirdParty/ffmpeg/licenses/ffmpeg_LICENSE.md
Support/ThirdParty/ffmpeg/licenses/x264_COPYING

I found the issue with video recording. The USD plugin wasn't loading properly, which I think is something related to the change from 2018.4 to 2019.4.
This doesn't fix the issue with the USD dll, but does prevent it not working from screwing over Open Brush.

Video recording

---

Assets/Prefabs/Panels/SketchbookPanel.prefab
Assets/Prefabs/Panels/SketchbookPanel_Mobile.prefab

Poly logo got changed to Open Brush during the initial rebrand. Poly is still a supported service (for now!). Will switch to Icosa later 😉

Corrected Poly logo

---

Assets/Scripts/CameraPathCaptureRig.cs
README.md

Fixes #47 
Who would have thought reading the README would be so useful!

Re-enable camera path recording

---

.github/workflows/build.yml
.github/workflows/pre-commit.yml
README.md

* Rename CI jobs
* Rename Github workflow files
* Document downloading and use of the bleeding edge releases

Improve and Document CI builds

---

README.md

Document new Oculus Unity package version

---

Assets/Editor/BrushLister.cs
Assets/Editor/BrushLister.cs.meta
Assets/Editor/PanelLister.cs
Assets/Editor/PanelLister.cs.meta

A couple of small editor menu item tools I use to get my bearings.

---

Assets/Editor/BrushLister.cs
Assets/Editor/BuildTiltBrush.cs
Assets/Scripts/App.cs
README.md

These are various minor changes I originally included in https://github.com/icosa-gallery/open-brush/pull/136.

Documentation cleanup

---

README.md

I might eventually move all of this readme to the docs but this will do for now

Update README.md to link to docs

---

Assets/Editor/GlTF_EditorExporter.cs
Assets/Scripts/Export/Export.cs

Not tested. I'll wait for the PR to generate a build and I'll test that

Always include textures in gltf exports

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml

Revert the hack of #166 , and use the latest release for dotnet/format.
Note that you may need to upgrade your local dotnet SDK to 6.0.100

Proper fix for dotnet-format

---

Assets/Prefabs/Panels/PolyPanel.prefab
Assets/Prefabs/Panels/PolyPanel_Mobile.prefab
Assets/Prefabs/Panels/SketchbookPanel.prefab
Assets/Prefabs/Panels/SketchbookPanel_Mobile.prefab
Assets/Prefabs/PopUps/PopUpWindow_Accounts.prefab
Assets/Prefabs/PopUps/PopUpWindow_AccountsMobile.prefab
Assets/Scripts/GUI/PolyPanel.cs
Assets/Scripts/GUI/SketchbookPanel.cs
Assets/Scripts/Sharing/VrAssetService.cs

* revert #86 and #91
With Poly shutting down, we can remove these temporary messages
* Disable Poly, but not GDrive
* remove mention of poly in accounts window
* fix formatting

Disable Poly (#139)

---

Assets/Materials/IntroMaterials/Intro_Logo.mat
Assets/Materials/IntroMaterials/Intro_Logo.mat.meta
Assets/Materials/IntroMaterials/Shaders/Intro_LogoImage.shader
Assets/Materials/IntroMaterials/Shaders/Intro_LogoImage.shader.meta
Assets/PlatformConfigMobile.asset
Assets/PlatformConfigPC.asset
Assets/Prefabs/Intro/openbrush_intro_full.prefab.meta
Assets/Prefabs/Intro/openbrush_intro_simple.prefab.meta

Update the logo to Open Brush! It's currently using a modified loading progress shader, which we can swap out for a properly drawn one later.

Add Open Brush startup logo

---

Assets/Prefabs/Panels/AdvancedToolsPanel.prefab
Assets/Prefabs/Panels/AdvancedToolsPanel_Mobile.prefab
Assets/Scenes/Main.unity
Assets/Scripts/Commands/SnipStrokeCommand.cs
Assets/Scripts/Commands/SnipStrokeCommand.cs.meta
Assets/Scripts/SketchMemoryScript.cs
Assets/Scripts/Tools/BaseTool.cs
Assets/Scripts/Tools/SnipTool.cs
Assets/Scripts/Tools/SnipTool.cs.meta

Seems to work ok enough to push out to our brave beta testers.

Snip tool to split strokes

---

Assets/Scripts/Commands/SquashLayerCommand.cs

FIx a bug where undoing "squash layers" didn't move strokes back to the layer they were previously on.

Fix undo for squash layer command

---

.github/workflows/build.yml
Assets/Editor/BuildTiltBrush.cs

Upgrade to newly release v2 actions (we were on v2-alpha-foo)
Remove the meaningless 'fail-fast' from non matrix stages

GitHub actions cleanup

---

Assets/Scenes/Main.unity

Turns out we already support webm on Windows - with transparancy!

Add webm to the list of allowed video types

---

.github/workflows/build.yml

…h events (xr_v2 only). Revert before merging

TEMP: Don't push to steam on pull request syncronize events, just push events (xr_v2 only). Revert before merging

---

.github/workflows/build.yml

* Upgrade cache version
* Don't restore from different Unity versions
* Switch key, to force new caches

Github Actions cache changes

---

Assets/XR/Settings/Open XR Package Settings.asset

Depth Submission can improve warping on some XR headsets

Use Depth Submission Mode

---

.gitignore
Assets/Manifest.asset
Assets/Oculus/OculusProjectConfig.asset
Assets/Oculus/OculusProjectConfig.asset.meta
Assets/Plugins/Android/AndroidManifest.xml
Assets/Resources/EnvironmentPrefabs/Passthrough.prefab
Assets/Resources/EnvironmentPrefabs/Passthrough.prefab.meta
Assets/Resources/Environments/Passthrough.meta
Assets/Resources/Environments/Passthrough/Passthrough.asset
Assets/Resources/Environments/Passthrough/Passthrough.asset.meta
Assets/Scripts/PassthroughManager.cs
Assets/Scripts/PassthroughManager.cs.meta
Assets/Scripts/VrSdk.cs

Enables passthrough mode on Quest and adds a new environment called 'Passthrough' to the environments panel 🚀
I still need to explore if we can add this capability on other platforms, would love to get Vive/Index working but I hear it's quite a hack. Passthrough is managed programmatically so should be quite easy to extend on other platforms as and when supported!

Add Passthrough environment on Quest

---

Assets/Editor/BuildTiltBrush.cs

Manifest was being overridden by our build script. whoops!

Actually fix Oculus builds

---

Assets/Editor/BuildTiltBrush.cs
Assets/Scripts/App.cs

Build scripts weren't copying textures for experimental brushes 

---

Assets/Scripts/API/ApiMethods.cs
Assets/Scripts/Commands/ClearLayerCommand.cs
Assets/Scripts/Commands/DeleteLayerCommand.cs
Assets/Scripts/Commands/SquashLayerCommand.cs
Assets/Scripts/Export/ExportCollector.cs
Assets/Scripts/Export/ExportUtils.cs
Assets/Scripts/Layers/LayerUI_Manager.cs
Assets/Scripts/Save/SketchWriter.cs
Assets/Scripts/SceneScript.cs
Assets/Scripts/SelectionManager.cs
Assets/Scripts/Widgets/GrabWidget.cs
Assets/Scripts/Widgets/ImageWidget.cs
Assets/Scripts/Widgets/ModelWidget.cs
Assets/Scripts/Widgets/StencilWidget.cs
Assets/Scripts/Widgets/VideoWidget.cs

Progress will be tracked on #283

Layer fixes

---

Assets/Scripts/Layers/LayerUI_Manager.cs

Opening a new sketch didn't set layer widgets up correctly.

Layers panel wasn't being initialized at the right times.

---

Assets/Scripts/Batching/Batch.cs
Assets/Scripts/Export/ExportUtils.cs

Reverts c8ee2c93ba36be62f2274026804f0212ff10c5f4

Undo large mesh support as it causes issues in SDK/Toolkit imports

---

Assets/Scripts/Save/SketchWriter.cs

Fix for merging strokes from sketches after layers feature added

---

Assets/ThirdParty/UnityODS/Materials/Warp2.shader
Assets/ThirdParty/UnityODS/Scripts/HybridCamera.cs

Fixes ODS 360 stereo rendering mode on Windows.
Fixes #356

Fix stereo recording mode on Windows

---

.github/workflows/build.yml

* File name should contain the version
* ZIP should not contain any subdirectories

Fix Pimax release; versioned files numbers and directory packaging

---

.github/workflows/build.yml

* Fix escaped quotes in beta release notes
* Combine dependencies and maintenance PRs, and add a category for build infrastructure stuff, to keep it separate from actual app features

Release note tweaks

---

.github/workflows/delete_branch_cache.yml

Followup to #395 , to address a few quirks

Improve cache management in build system, part 2

---

Assets/Prefabs/VrSystems/VrControllers/UnityXR/UnityXRWmrControls.prefab
Assets/Scripts/Input/UnityXRControllerInfo.cs
Assets/Scripts/Input/UnityXRFakeThumbTouchComposite.cs
Assets/Scripts/Input/UnityXRFakeThumbTouchComposite.cs.meta
Assets/Scripts/Input/UnityXRInput.inputactions
Assets/Scripts/Input/UnityXRInputAction.cs
Assets/XR/Settings/Open XR Package Settings.asset

Fixes #376 
Controller rotation may be off, requesting some tests!

Enable Microsoft motion controller profile (WMR)

---

.github/workflows/build.yml

Add the author's name to the release note, and put everything on one line

Change release note formatting

---

Assets/Settings/Localization/Chinese (Simplified) (zh).asset
Assets/Settings/Localization/French (fr).asset
Assets/Settings/Localization/German (de).asset
Assets/Settings/Localization/Japanese (ja).asset
Assets/Settings/Localization/Korean (ko).asset
Assets/Settings/Localization/Localization Settings.asset
Assets/Settings/Localization/Spanish (es).asset

Will prevent Open Brush automatically switching language until we've added in the right fonts.

Temp remove system locale selector

---

Assets/Scenes/Main.unity

See https://discord.com/channels/783806589991780412/1054686775504797816/1115999987919225025
> Using the plugin scripting build but not sure if it's for all :   When I record freehand and stop and attempt a second time, the camera freezes and you can no longer use the app.  Needs a restart each time.

Add missing swipe hint to Multicam tool

---

Assets/Scripts/App.cs

Leave a text file in the original location explaining the change

Move user folder to Application.persistentDataPath

---

Assets/Prefabs/ControllerHint.prefab

Fixes a bug @zandyxr reported on Discord when recording using the Snapshot/Multicam tool

Multicam recording fix

---

Assets/Prefabs/Panels/AdminPanel.prefab
Assets/Scenes/Main.unity

Fix a few of the promo popups that needed localized properly.

Fix missing localization for a few promo popups

---

.github/workflows/build.yml

Restore Steam password; it seems to be needed

---

Assets/Prefabs/Panels/LabsPanel.prefab
Assets/Scripts/WebcamSurface.cs

Hopefully now everything webcam related is hidden behind #if !UNITY_ANDROID
Followup to #477

Fix webcam breaking Oculus builds

---

Assets/Prefabs/SymmetryWidget.prefab

Wallpaper symmetry visualisations were offset +15 by mistake

---

Assets/Materials/ReferenceImage.mat
Assets/Scripts/Commands/MultimirrorDuplicateCommand.cs
Assets/Scripts/Save/MetadataUtils.cs
Assets/Scripts/Save/SketchMetadata.cs
Assets/Scripts/Widgets/ImageWidget.cs
Assets/Scripts/Widgets/Media2dWidget.cs
Assets/Scripts/Widgets/VideoWidget.cs
Assets/Shaders/ReferenceImage.shader

There's no UI to change this manually at the moment but it's "doing the right thing" in terms of behaving intuitively and not breaking existing behaviour.

Support per widget setting for two sided and set it to true when duplicating to multimirror

---

Assets/Materials/ControllerPad_ChangeSliderValue.mat
Assets/Materials/ControllerPad_ChangeSliderValue.mat.meta
Assets/Materials/ControllerPad_ChangeSliderValueActive.mat
Assets/Materials/ControllerPad_ChangeSliderValueActive.mat.meta
Assets/Prefabs/Panels/Widgets/AdvancedSlider.prefab
Assets/Scenes/Main.unity
Assets/Scripts/GUI/AdvancedSlider.cs
Assets/Scripts/GUI/BasePanel.cs
Assets/Scripts/GUI/BaseSlider.cs
Assets/Scripts/Input/ControllerGeometry.cs
Assets/Scripts/Input/ControllerMaterialCatalog.cs
Assets/Shaders/ChangeSliderValue.shader
Assets/Shaders/ChangeSliderValue.shader.meta

If you want to test this then try any of the sliders in the multimirror popup.

Thumbstick changes AdvancedSlider value + visual feedback on controller model

---

Assets/Prefabs/Panels/SettingsPanel_Mobile.prefab

Quick fix for an NRE introduced by #532

hotfix experimental mode toggle

---

.github/workflows/build.yml
Assets/Editor/BuildTiltBrush.cs
Assets/Prefabs/PopUps/PopUpWindow_Accounts.prefab
Assets/Scenes/Main.unity
Assets/Scripts/Config.cs
Assets/Scripts/GUI/ProfilePopUpWindow.cs
Assets/Settings/Localization/Strings/Strings Shared Data.asset
Assets/Settings/Localization/Strings/Strings_en.asset

Slightly alters build pipeline to include a CLI to disable the account sign-in panel when building for unsupported regions.

[Pico] Add Chinese build, disable accounts

---

Assets/Scenes/Main.unity

DisableAccountLogins is a collateral change from saving but I presume it's correct.

Switch main scene sdk mode back to OpenXR

---

.github/workflows/build.yml
Assets/Editor/BuildTiltBrush.cs

Fixes Unity activation, which has been broken on the Unity side.
However, this does not currently support builds from PRs from forks. We now need to pass a username & password as well as a license file if we use a personal license, which we do for builds from forks, since forks can't access the secrets where we store our Pro license.
Sample showing that it builds: https://github.com/icosa-foundation/open-brush/actions/runs/6930830858

Update game-ci build to v4

---

Assets/Scripts/Commands/MultimirrorDuplicateCommand.cs

I must confess that some of this is guesswork. I've really struggled with this method and revisited it multiple times. I'm not entirely clear about the correct logic for undo but this seems less buggy than before at least.

This seems to fix most bugs with duplicating to multimirror.

---

Assets/Scripts/Rendering/FfmpegPipe.cs
Assets/Scripts/Rendering/VideoRecorderUtils.cs

Also fixes editor only bug with video recording

Video batch file fix

---

Assets/Prefabs/VrSystems/ControllerGeometries/KnucklesLeftControllerGeometry.prefab
Assets/Prefabs/VrSystems/ControllerGeometries/KnucklesRightControllerGeometry.prefab
Assets/Prefabs/VrSystems/ControllerGeometries/PicoNeo3LeftControllerGeometry.prefab
Assets/Prefabs/VrSystems/ControllerGeometries/PicoNeo3RightControllerGeometry.prefab
Assets/Prefabs/VrSystems/ControllerGeometries/PicoPhoenixLeftControllerGeometry.prefab
Assets/Prefabs/VrSystems/ControllerGeometries/PicoPhoenixRightControllerGeometry.prefab
Assets/Prefabs/VrSystems/ControllerGeometries/ViveControllerGeometry.prefab
Assets/Prefabs/VrSystems/ControllerGeometries/WmrLeftControllerGeometry.prefab
Assets/Prefabs/VrSystems/ControllerGeometries/WmrRightControllerGeometry.prefab

Temp revert of controller i18n for latest release while we work on the fixes in #555

Temp revert controller i18n

---

Assets/Prefabs/Panels/SketchbookPanel.prefab
Assets/Prefabs/PopUps/PopUpWindow_SketchbookMenu.prefab
Assets/Prefabs/PopUps/PopUpWindow_SketchbookMenuMobile.prefab

Various fixes:
1. Deleting sketches
2. Renaming keyboard positioning
3. Hide the poly button

Fixes for Sketchbook and popup

---

Assets/Editor/BuildTiltBrush.cs

From https://discord.com/channels/783806589991780412/803747594378936361/1183251540262277135 . Links to sample runs are there

Catch exceptions in DoBuild() and print them in a way that Github will highlight

---

.github/workflows/build.yml
.github/workflows/get_license.yml

Update artifact actions from v3 to v4

---

Assets/Prefabs/Panels/AdvancedToolsPanel_Mobile.prefab

Prefab had reverted back a bunch of settings. (probably a bad merge)

Fix Mobile advanced tools panel

---

README.md

Closes #616 Thanks to @chengnay

Update info on setting up Google API

---

Assets/Scripts/SelectionManager.cs
Assets/Scripts/SketchMemoryScript.cs
Assets/Scripts/WidgetManager.cs

Very strange that this was overlooked and not reported for so long.

Fix select all and invert selection for non-main layers

---

fastlane/Fastfile

This same code seems to have finished almost everything from the CLI, so hopefully, maybe...

Fix (again) the fastlane upload to the app store

---

Assets/Scripts/Brushes/BrushDescriptor.cs
Assets/Scripts/CameraPathCaptureRig.cs
Assets/Scripts/Environment.cs
Assets/Scripts/GUI/AdminPanel.cs
Assets/Scripts/GUI/AudioVizPopUpWindow.cs
Assets/Scripts/GUI/BasePanel.cs
Assets/Scripts/GUI/LightsPanel.cs
Assets/Scripts/GUI/ModelButton.cs
Assets/Scripts/GUI/OptionButton.cs
Assets/Scripts/GUI/PolyPanel.cs
Assets/Scripts/GUI/SketchbookPanel.cs
Assets/Scripts/GUI/UIComponent.cs
Assets/Scripts/Layers/LayerUI_Manager.cs
Assets/Scripts/LoadingScene.cs
Assets/Scripts/OverlayManager.cs
Assets/Scripts/ReferencePanelTab.cs
Assets/Scripts/Sharing/ProfileButton.cs
Assets/Scripts/TiltMeterScript.cs
Assets/Scripts/TutorialCard.cs
Assets/Scripts/Tutorials/HintObjectScript.cs
Assets/Scripts/Tutorials/PromoManager.cs
Assets/Settings/Localization/Localization Settings.asset
Assets/ThirdParty/UltimateXR Keyboard/KeyboardKeyUI.cs

- Default to system locale if playerPref isn't set yet
- use Async method of fetching localized content - this fix is for WebGL support 👀

Localization Fixes

---

.github/workflows/build.yml

Fix DMG notarization (though I don't know why it chose to break now!), and decouple the Steam release from the notarization

DMG Issues

---

Assets/Scripts/VrSdk.cs

https://developer.oculus.com/documentation/unity/ps-age-group-apis/

Compliance with Meta Age Group API requirements

---

Assets/Editor/Tests/TestExport.cs
Assets/Editor/ToolkitUtils.cs
Assets/Scripts/API/ApiManager.cs
Assets/Scripts/API/ApiMethods.Utils.cs
Assets/Scripts/Export/Export.cs
Assets/Scripts/Export/ExportFbx.cs
Assets/Scripts/Export/FbxUtils.cs
Assets/Scripts/Export/ImportMaterialCollector.cs
Assets/Scripts/FbxReader.cs
Assets/Scripts/GUI/PanelManager.cs
Assets/Scripts/Model.cs
Assets/Scripts/OverlayManager.cs
Assets/Scripts/Util/SerializableGuid.cs
Assets/Scripts/WidgetManager.cs

Mostly stuff hidden by compiler directives or not covered by our automatic formatting.

Minor formatting improvements

---

Assets/Scripts/PointerManager.cs

Allow generation of sphere with gesture on mobile

---

.github/workflows/build.yml

Fix github release (typo in directory name)

---

.github/workflows/build.yml

Fix artifact upload of development builds

---

Assets/Scenes/Main.unity

Shift the preview down so it doesn't overlap the hint

---

.github/workflows/build.yml

Also update measurements as of Aug 2 2024

Remove more unneeded files to free more disk space

---

.editorconfig
.yamlfmt

A few commits from PR #774 that belong on their own

Improve Windows development experience

---

.github/workflows/highlight_manual_review_files.yml

Fix missing line that caused duplicate comments

---

.github/workflows/periodic_rebuilds.yml

* AI hallucination
* Add missing checkout
* Fix rerun endpoint
(followup to #858 )

Fix broken workflow

---

Assets/Editor/Tests/TestBrush.cs
Assets/Scripts/InitNoHeadsetMode.cs
Assets/Scripts/Save/SaveLoadScript.cs
Assets/Scripts/Save/SketchWriter.cs
Assets/Scripts/SceneScript.cs
Assets/Scripts/SketchControlsScript.cs

1. Merged strokes are added to a new layer
2. Timestamps should start after existing timestamps
3. Bug in selections for merge strokes should be fixed

Fix various issues related to additive loading

---

Assets/Scripts/Rendering/StillFrameSequenceExporter.cs
Assets/ThirdParty/Logitech/Scripts/VrStylusHandler.cs

PR 893 minor fixes
