Assets/Scripts/UserConfig.cs
Thanks to pld, we found that the experimental brushes setting being changed by UserConfig.cs and dependent on being in the Unity Editor. Changed it to be dependent on the experimental setting changed in Tilt>Build>Experimental setting.
=> Experimental Brushes outside the editor

Assets/Scripts/UserConfig.cs
I believe with the current build, experimental brushes may not show in the editor due to settings being overwritten by UserConfig, I should have tested more thoughly before merging my last PR, apologies. 
Opening this small PR as I noticed people forking us, I did not want them to struggle getting experimental brushes.
=> Enable ExperimentalBrushes in Editor too

Assets/Scenes/Main.unity, Assets/Scripts/App.cs
**First Commit**
Store exports in Documents/OpenBrush not TiltBrush, and use separate Open Brush config file.
Note to devs: 
I hope you did not clone the repo as C:\Users\{USER}\Documents\Open Brush\
or your might get Sketches in your repo.
**Second Commit**
Changed the version number to 0.1.0 as requested by @mikeskydev
=> Use separate export folder and config for Open Brush

Assets/Editor/BuildTiltBrush.cs, Assets/Scripts/App.cs, ProjectSettings/ProjectSettings.asset
Some small fixes for the Quest version:
Gradle requires a android build number higher than 0: moved it to 1
Changed the default bundle name to not include `.apk`, while preserving it on the output file.
=> Fixes for Quest version

ProjectSettings/ProjectSettings.asset
More fixes building upon #14:
Changed Android SDK to version 26, from 28. This was the version set in the original release, and fixes an issue related to saving permissions in higher SDK versions. This will be replaced in the future with the correct fixes for higher SDK versions.
Changed color space to gamma, matching the shipped Tilt Brush color space.
=> Fix saving on Quest

Assets/Scripts/VrSdk.cs
Fixes crash on: https://github.com/icosa-gallery/open-brush/issues/7.
Head tracking is still disabled when profiling. ~~It looks intentional, but I'm not sure.~~ It is intentional
=> Add nullcheck when enabling profiling

Assets/Editor/BuildTiltBrush.cs, Assets/Editor/BuildWindow.cs
Fix build window, adb, and background builds (should also help on Linux, by using rsync instead of robocopy, but I didn't test anything on Linux.
=> Fixes for developing on OS X

Support/fbx/README.md
actually try this, find that you also need to add `FBXSDK_RUNTIME`.
If you don't add it, you will get the following error message when building
```
error CS0246: The type or namespace name 'Autodesk' could not be found (are you missing a using directive or an assembly reference?)
````
sorry for your inconvenience.
This is a re-creation of Pull Requests #9 due to a change in the configuration of my repository.
=> update FBX Support Guide

Assets/Scripts/App.cs
=> Fix undefined reference to InitUsd.Initialize() on Quest 2

Assets/PlatformConfigPC.asset
Desktop GIF modes were left out of #15 to prevent a merge conflict, this enables them
=> Enable desktop GIF modes

ProjectSettings/ProjectSettings.asset, Support/Python/unitybuild/main.py
* Change target platform for Linux and OSX to match GUI
* Fix filename in python to be like App.cs
* Align the Python build directory (mostly) with the GUI paths
* Change the applicationIdentifier for Android to com.icosa.openbrush (this one was being overwritten correctly at build time anyway, but it'd be better to have the proper value always present)
=> Align Python build with C# builds

.github/workflows/unity.yml, Assets/Editor/BuildTiltBrush.cs
This requires the addition of 4 secrets:
ANDROID_KEYSTORE_BASE64 -- the output of `base64 -i foo.keystore`
ANDROID_KEYSTORE_PASS -- the password for the keystore
ANDROID_KEYALIAS_NAME -- the name of the alias
ANDROID_KEYALIAS_PASS -- should match KEYSTORE_PASS in our case
Because it uses Github secrets, it won't run on a fork, so we won't do
this for PRs. But anything coming from the main tree can use this.
We do still keep the github name in the package name, to differentiate
between a formal release and an unreleased candidate.
=> Sign all builds that are built from pushes to main

.github/workflows/build.yml
This means that pushes to a fork's main will not trigger a signed build
(which will fail) and PRs *to* forks will not run builds. PRs *from*
forks are unaffected.
=> Only run CI builds on icosa-gallery/open-brush

.github/workflows/build.yml
=> Re-enable builds on all forks, but only sign if the secrets are present

Assets/Scripts/Sharing/SketchfabService.cs
It looks like you're sending `source: "tilt-brush"` and tags `tags: ["tiltbrush"]` in the upload POST. If you change those to `open-brush` or `openbrush`, I'll take care of the rest on my end. Just let me know which you choose for each. - James Green, SketchFab
Let me do some more testing before merging.
=> Change SketchFab uploads to upload as Open Brush

.github/workflows/build.yml
This will allow users who have enabled Github Actions on their fork to create builds using CI without needing a local environment and without creating a PR just to build.
The current behavior of builds on PR submission + merge to main + tag with `vX.Y` is unaffected.
=> Build all commits with [CI BUILD] somewhere in the commit message

.github/workflows/build.yml
* Preserve permissions on the OS X artifact
* Correctly name the Application (OpenBrush, not OpenBrush-github) on release builds
=> Packaging improvements

Assets/Prefabs/Panels/PolyPanel_Mobile.prefab, Assets/Prefabs/Panels/SketchbookPanel_Mobile.prefab, Assets/Scripts/GUI/PolyPanel.cs, Assets/Scripts/GUI/SketchbookPanel.cs
A cleaner fix for disabling Poly on Quest 1 that doesn't block Quest 2.
Adds an extra popup to the Sketchbook and Poly panels notifying the user that the feature isn't available.
=> Disable Poly on Quest 1

.github/workflows/build.yml
Instead of saving a new cache for each commit that triggers a build, save one with the name based on the platform only. This will be built on main and used by an PRs, but not saved, since the name matches perfectly. If it ever gets out of date, it will need to be manually cleared (i.e., the name changed)
=> Do not save a cache for each commit

Assets/Scripts/GUI/PolyPanel.cs
Checks for the panel existing before disabling. d'oh.
Sidenote, why doesn't `m_NotSupportedMessage?.SetActive(false);` work here?
=> Fix Poly panel fix

.github/FUNDING.yml, Assets/Scenes/Main.unity, ProjectSettings/ProjectSettings.asset, README.md
Tidy up readme, update version numbers
=> Changes for 0.3.0 release

.github/workflows/build.yml, Assets/Editor/BuildTiltBrush.cs
In order to make it easier to run multiple versions, instead of a fixed
"-github" name (and package name of com.icosa.openbrushgithub), this
commit changes the logic for CI builds.
* Builds from PRs are named PR#xx (PRxx in the package name)
* Builds from branches (triggered with a [CI BUILD] tag) are named based on the branch
name. Special characters of /[#_-]/ are removed from the package name
* All commits on main have the same name, whether they're pre-release
builds or formal release builds. This means that the pre-release builds
will NOT have a unique name, but this will allow us to upload them to a
"beta" release channel
=> Name builds based on the source

.github/workflows/build.yml, Assets/Editor/BuildTiltBrush.cs, CI.md
Prerelease builds go to the Beta channels for both Rift and Quest (case doesn't matter)
Formal releases (tag) go to the Store channel
=> Upload builds to Oculus automatically

Assets/Editor/BuildTiltBrush.cs, README.md
This PR is for building own app with other scenes added for beginners.
- `README` - Add explanation about 'the way to build with new scenes added for beginner developers' in `Building your app for Oculus Quest` step.
- `BuildTiltBrush.cs` - Add explanation about 'the way to build with new scenes added for beginner developers' on 1221st line.
---
I'm a student making a project with `Open Brush` as an Open Brush sample project.
While making a new project, one of the most difficult things to solve was finding a way to add my new scenes in this project.
In the case of building in the way README file is letting people know, `Tilt > Build > Do Build`, new scenes are never added before change `BuildTiltBrush.cs` but this document isn't explaining this problem, and this is very difficult to solve …
=> Update README & BuildTiltBrush.cs for beginners

README.md
underscorediscovery now goes by ruby0x1. You can verify this at their
old gist page or website commented in the shader (TiltShift.shader):
https://gist.github.com/underscorediscovery/
http://notes.underscorediscovery.com/
Update link to point to their current tilt.shift.glsl gist which is mostly
similar to TiltShift.shader.
=> Readme: Fix dead link for Tilt Shift effect source

.github/workflows/build.yml
Addresses the build failure seen in #126 (it seems that il2cpp uses more space, but we're probably near the border anyway. That said, I only did it for Android because it does take a few minutes).
The cleanup is based on https://github.com/game-ci/docker/blob/main/.github/workflows/scripts/free_disk_space.sh and https://github.com/matrix3d/buildu3d/blob/main/.github/workflows/android.yml
=> Free some extra disk space before building (Android only)

.github/workflows/build.yml
Bad: `-btb-out /github/workspace/build/StandaloneLinux64-SteamVR/OpenBrush-features/betterbuildnames`
Good: `-btb-out /github/workspace/build/StandaloneLinux64-SteamVR/OpenBrush-featuresbetterbuildnames`
(well, relatively good, I suppose)
=> Remove / in build identifier (messes with directory names)

Assets/Prefabs/Panels/PolyPanel.prefab, Assets/Prefabs/Panels/PolyPanel_Mobile.prefab, Assets/Prefabs/Panels/SketchbookPanel.prefab, Assets/Prefabs/Panels/SketchbookPanel_Mobile.prefab, Assets/Prefabs/PopUps/PopUpWindow_Accounts.prefab, Assets/Prefabs/PopUps/PopUpWindow_AccountsMobile.prefab, Assets/Scripts/GUI/PolyPanel.cs, Assets/Scripts/GUI/SketchbookPanel.cs, Assets/Scripts/Sharing/VrAssetService.cs
Poly has reached EOL.
This PR reverts previous changes of #86 and #91, which were causing issues in experimental builds.
A message has been added about Poly EOL and any checks of the VR Asset Service's status return disabled.
The Poly code has been left intact as a basis for Icosa integration later.
NOTE: I haven't had a chance to test this on hardware yet, will do so tomorrow!
=> Disable Poly

Assets/Scripts/VrSdk.cs
Open Brush currently uses the `OculusMRCCameraUpdate` script that obtains the mixed reality camera pose from the Oculus SDK, converts it back into the stage coordinate space that the Oculus uses internally, scales it by 10x, then tells the Oculus SDK to use the scaled pose for the mixed reality camera.
This script also had a small bug where this calculation was only done once, so if the physical camera moves, the virtual camera would be positioned incorrectly. Instead, I add an OVRCameraRig to the VrSystem GameObject, which is already scaled properly, as recommended by the Oculus documentation. 
https://www.youtube.com/watch?v=ZDZwRU1mIfk
=> Add an OVRCameraRig to the VrSystem object for MRC on Quest

Assets/ThirdParty/TiltBrushToolkit/Scripts/Gltf/GltfMaterialConverter.cs
Example file: https://sketchfab.com/3d-models/persimon-whole-cut-and-seed-346d0b5a95c94c2890dbff3b38984719 (download as "gltf converted" and import via the media library). In general I think "try as hard as possible to import without throwing an error" is probably a good import strategy.
=> Fix an error importing some Sketchfab gltf files

.github/workflows/pre-commit.yml
The latest dotnet-format is 7.0.x and does not run with .NET 3.1.2 or 5.x, which is the stable release. We could move to a preview release, but there are two open issues on dotnet format; see 1317 and 1318 at their repo.
However, the way pre-commit handles dotnet packages, it always installs the latest version (dotnet tool install ...). There is no way to specify a specific version.
So we have this charming hack to trick pre-commit into using our manually installed version.
=> Pin dotnet-format to 5.1.225507

Assets/Shaders/TiltBrushLogo_Progress.shader
The shader displaying the loading progress was designed specifically for the Tilt Brush logo. However this doesn't work with the Open Brush logo. The shader has been simplified to work better with the Open Brush logo.
Before:
After:
=> Alter progress shader for OB logo

.github/workflows/build.yml
Pre-release builds are pushed to the `<os>-beta` and `<os>-beta-experimental` channels.
Release builds will go to `<os>-release` and `<os>-release-experimental`.
A secret named BUTLER_CREDENTIALS should be created, with a valid API
key.
=> Push builds to Itch

Assets/Scripts/Export/ExportLatk.cs
Added a check for strokes marked deleted, to keep them from being included in the export.
=> Don't included deleted strokes when exporting LATK

.github/workflows/build.yml
Reverts icosa-gallery/open-brush#207
Github doesn't handle more than one pending job. This makes this unsuitable for our purposes. (There was also a missing $, but even with that done properly, the current behavior which only allows one pending action is insufficient)
=> Revert "Prevent more than one build at a time on a given branch. Will prevent merge timing bugs"

Assets/Scripts/ReferenceVideo.cs
It seems that one of the os updates on quest 2 broke the video playback in media library.
I saw multiple threads on similar issues and it looks like android 10 handles file access differently than on previous version.
https://forum.unity.com/threads/error-videoplayer-on-android.742451/#post-5028434
https://issuetracker.unity3d.com/issues/android-video-player-cannot-play-files-located-in-the-persistent-data-directory-on-android-10
=> Fixed video reference on quest 2

Assets/Shaders/SnapshotCameraFlash.shader
Fixes #45, at least in the viewfinder. This may be part of a bigger set of issues related to the postprocessing shader stack, but this will restore the viewfinder functionality for now!
=> Fix invisible camera viewfinder when no posteffects

.github/workflows/get_license.yml
This workflow is triggered manually, and can be used to create the files
needed to store a license in the build.yaml. This license contains the
credentials used for non-official builds; i.e., PR builds, and builds on
forks that do not have the secrets defined for using a real license.
If you want to create your own file, or need to move to a newer major
Unity release, follow the instructions at https://game.ci/docs/github/activation
=> Add workflow to generate the unity license file for the embedded license (non formal PRs)

.github/workflows/build.yml, ProjectSettings/ProjectSettings.asset
In #217, it was enabled in the ProjectSettings file. However, this broke
local compilation, since the keystore was not available for repo
clones/forks.
It's better to leave it disabled, and just enabled it in all CI builds
(where we use either the real keystore for formal builds, or our fake
one for PRs)
=> Disable custom keystore in repo; enable it for all CI builds

Assets/ThirdParty/TiltBrushToolkit/Scripts/Gltf/GltfMaterialConverter.cs
Minor fix. Still fails on lots of files in https://github.com/KhronosGroup/glTF-Sample-Models but this fixed GlamVelvetSofa and maybe a few others.
=> GLTF import fix

.github/workflows/build.yml, ProjectSettings/ProjectSettings.asset
- Add generic OpenXR on Android
- Removes `OCULUS_SUPPORTED` from Android scripting define symbols. CI will add this automatically.
=> Add Android OpenXR

.github/workflows/build.yml, Assets/Editor/BuildTiltBrush.cs, Assets/Scripts/VrSdk.cs, Assets/XR/Settings/Open XR Package Settings.asset, Packages/manifest.json, Packages/packages-lock.json
Switches Oculus to build via Unity's OpenXR rather than Oculus's custom plugin 🎉
- Removes Oculus' plugin from the package manager.
- update to v39 of the Oculus SDK to enable the new OpenXR Feature.
- new IDisposable for managing OpenXR features.
=> Oculus via Unity OpenXR

Assets/Prefabs/HttpServer.prefab
Login on desktop has been broken for too long while waiting on #232. This PR temporarily removes the YouTube additional scopes allowing the functionality to be restored. Will revert this commit as part of #232 instead.
=> Fix: Temporarily remove YouTube scopes

Assets/Scripts/Save/SketchWriter.cs
Groups with both strokes and models in them were splitting into separate groups after save/load. This bug was introduced by the merge strokes feature.
=> Fix for groups bug

Assets/Scripts/API/ApiManager.cs, Assets/Scripts/API/CollectionUtils.cs, Assets/Scripts/API/CollectionUtils.cs.meta
We were referencing Valve's Newtonsoft just for a single extension method
=> Remove reference to Valve Newtonsoft 

Assets/Shaders/ColorPicker.shader, Assets/Shaders/ColorPicker_hs_l.shader, Assets/Shaders/ColorPicker_hs_logv.shader, Assets/Shaders/ColorPicker_sl_h.shader, Assets/Shaders/ColorPicker_sv_h.shader, Assets/Shaders/Include/Brush.cginc, Assets/Shaders/Include/ColorSpaceConvert.cginc, Assets/Shaders/Include/ColorSpaceConvert.cginc.meta
Performs a gamma to linear conversion of the palette on the color picker panel.
I've moved the color space changes from Brush.cginc to their own file to prevent cyclical redefinition.
Thanks to @ZandyXR for flagging the issue!
=> Correct color picker visual from gamma to linear

Assets/Scripts/Widgets/StencilWidget.cs
When we added planar stencil we accidentally broke loading sketches that use it in older versions of TIlt Brush/Open Brush. This change prevents similar issues in future.
=> Load sketches even with unknown stencil types

Assets/Editor/BuildTiltBrush.cs, Assets/Plugins/Android/AndroidManifest.xml, ProjectSettings/ProjectSettings.asset
Updates apk package name to reflect our correct domain as we publish to more platforms.
Override specifically for Oculus platform as we're already published there so we're locked in.
=> Update Android base package name

Packages/manifest.json, Packages/packages-lock.json
Switches back to using Unity's version of Newtonsoft JSON by using a modified dependency of Google API core hosted on our mirror repo.
This gives us more flexibility when it comes to adding other packages, like glTF importers and localization.
=> Custom google api core with Unity's Newtonsoft JSON

.github/workflows/build.yml
Changes CI to upload to `beta` and `beta-experimental` branches instead of `prerelease`, to make things clearer to the end user.
=> Change Steam beta branch names

Assets/Scripts/Stroke.cs
After loading a sketch with a missing brush, any attempt to load a new sketch fails unless you restart.
=> Unknown brush breaks loading

.github/workflows/build.yml, .github/workflows/get_license.yml, .github/workflows/pre-commit.yml
* Replace actions/checkout@v2 with @v3 (fixes node 12 deprecation warning)
* Replace actions/{upload,download}-artifact@v2 with @v3
* Replace ::set-output with >> $GITHUB_OUTPUT
=> Fix build warnings

.github/workflows/build.yml
* Fix setup-steamcmd by upgrading the v1.1.5
* Replace softprops/action-gh-release with koplo199's fork, because these two issues have gone unaddressed:
https://github.com/softprops/action-gh-release/issues/249
https://github.com/softprops/action-gh-release/issues/265
(both have duplicates, but these are the oldest reported issue)
=> Fix build warnings that only showed up when releasing a version

Assets/Editor/BuildTiltBrush.cs
Fixes an issue where we were setting mobile config on android builds, but it wasn't properly added to the build as the config file wasn't marked as changed. This caused a number of 'issues' that didn't have much real-world performance consequences, but produced errors such as
- Using the full version of the intro sketch, instead of the optimised one
- Video listed on the multi-cam tool
- no memory limit panel appearing
=> Mark config dirty on build

Assets/Editor/BuildTiltBrush.cs
This is pre-work for wave SDK, which currently requires GLES 3.0 while we use Vulkan right now. This may also help our Pico builds.
=> Change graphics backend per platform

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, Assets/Scripts/AudioManager.cs, Assets/Scripts/GUI/FloatPropertySlider.cs, Assets/Scripts/GUI/GpuTextRender.cs, Assets/Scripts/Input/BaseControllerBehavior.cs
Fix dotnet-format in pre-commit
.NET has moved to 7.x, and with it, pre-commit no longer installs
dotnet-format properly. It gives this error:
[INFO] Initializing environment for https://github.com/dotnet/format.
[INFO] Installing environment for https://github.com/dotnet/format.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/bin/dotnet', 'tool', 'install', '--tool-path', '/Users/FOO/.cache/pre-commit/repoXXXXXXXX/dotnetenv-default/bin', '--add-source', 'pre-commit-build', 'dotnet-format')
return code: 1
expected return code: 0
stdout:
/var/folders/0b/mq_jkw6n6x75xr18vy44lmb40000gn/T/ab063401-9d0d-4610-a73d-6db1b84c23b8/restore.csproj : error NU1100: Unable to resolve …
=> Fix dotnet format in CI (and possibly locally)

.github/workflows/build.yml
Specifically, Pico needs a unique cache from Quest/Android generic.
Also stop disabling swap; we need the extra memory, especially for Pico builds.
=> Use a unique cache for each platform/rendering backend

.github/workflows/build.yml, ProjectSettings/ProjectSettings.asset
Before, we passed through ASTC as a build option for all android builds, but we can just set it as default instead
=> Set ASTC to default tex format for android

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/pre-commit.yml
* pre-commit time reduced from ~2:10 to ~1:00 on subsequent runs on a branch by using a manual cache
* Same improvement applied to the first run, by (creating and) using the cache from main
* Free space increased from ~48GB to ~51GB for Android builds (initial free space without this step is ~31GB, which is not enough). Other platforms don't need the extra space, so we skip this step (takes ~2:20)
* Three warnings removed from older actions
* Enable dependabot for github actions
=> Build tweaks and improvements

.github/workflows/build.yml
We used to need this, but we no longer do (tested even with a clean build without any caches). Removing it saves ~2:30 on Android builds (negligible on a clean build, but about 10% of a cache build).
=> Disable the image cleanup for Android

.github/workflows/build.yml
After PR #344, the same build serves both regular mode and experimental mode, but people who are on either beta-experimental (the new name) or prerelease-experimental (the old name, see PR #291 and #315 for details) should get this build too.
Once 2.0 is released, we'll delete all the channels except "beta" and everyone will default to the formal release.
=> Continue uploading builds to Steam's '*-experimental' branches

Assets/Scripts/Rendering/RenderWrapper.cs, Assets/XR/Settings/Oculus Settings.asset
Makes changes to the enabled features on Quest based on the documentation provided for the plugin: https://docs.unity3d.com/Packages/com.unity.xr.oculus@3.2/manual/index.html
This appeared to allow us to re-enable MSAA for android! Will need to test all platforms though.
=> Improve Quest config settings

Assets/Prefabs/Panels/AdvancedToolsPanel.prefab, Assets/Prefabs/Panels/AdvancedToolsPanel_Mobile.prefab, Assets/Prefabs/Panels/ExtraPanel.prefab, Assets/Prefabs/Panels/ExtraPanel_Mobile.prefab, Assets/Prefabs/Panels/LabsPanel.prefab, Assets/Prefabs/Panels/LabsPanel_Mobile.prefab, Assets/Prefabs/Panels/ToolsPanel_Mobile.prefab
Switches the Poly button in the Extra panel for the Reference Library icon in the Labs panel.
This is just to make it easier to find, we'll revisit post-2.0 for how to manage multiple asset providers nicely.
Also moved the camera tool from labs to advanced tools on mobile, and additionally added the options panel on longpress.
=> Swap Reference and Poly icon positions

.github/workflows/build.yml
After the merge of v2.0, stop uploading explicit experimental builds to Steam, since they're included after PR #344 (see also #346 ). 
We'll delete the prerelease-experimental and beta-experimental, and users will switch automatically to the main release channel.
Similarly, following #291 (and #315), we'll be deleting the prerelease channel; users who want the tip builds should switch to the beta channel.
This all needs to go into the release announcement
=> Remove upload of experimental build(s) and pre-release channel for Steam. Just keep beta channel

.github/workflows/build.yml
PowerShell does not include the current directory in the path by default. This should address this; the login flow was tested, but the actual upload has not been tried yet.
=> Fix Pimax upload, and temporarily enable it for all pushes to main

.github/workflows/build.yml
=> Don't show "uncategorized" in the release notes if it's empty

.github/workflows/build.yml
Current uploads all pushes to main. Once this is working, we'll skip the non official builds, just like we're going to do for Pimax
=> Upload builds to Viveport automatically

.github/workflows/build.yml
Followup to #381 and #377; platforms that don't support release channels should only get formal builds.
=> Disable the automatic push of builds to Pimax and Viveport for non-formal builds

.github/workflows/build.yml
Formal releases will use a manually written user focused release notes, but for automatic beta releases, send the list of commits and PRs.
Since we only show people the option to download the latest beta, include all commits since the previous formal release
Sample release note:
```
2.0.1-g7cc91ef: Remove upload of experimental build(s) and pre-release channel for Steam. Just keep beta channel (#371)
2.0.2-g6dee03d: Fix Pimax upload, and temporarily enable it for all pushes to main (#377)
2.0.3-g94fe2e2: Fix Pimax release; versioned files numbers and directory packaging (#379)
2.0.4-g97dc47b: Automatically generate changelog, rather than doing it manually (#380)
2.0.5-g72106c7: Don't show "uncategorized" in the release notes if it's empty (#384)
2.0.6-g8a22109: Upload builds to Viveport …
```
=> Send a "raw" changelog to Oculus for Beta releases

Assets/Prefabs/Panels/AdvancedToolsPanel.prefab, Assets/Prefabs/Panels/AdvancedToolsPanel_Mobile.prefab, Assets/Scripts/Input/UnityXRControllerInfo.cs, Assets/Scripts/SketchControlsScript.cs
Fix advanced panel's half height, will snap properly now.
Fix camera switching on vive wands. a bit hacky but it's pretty annoying!
=> Launch fixes

.github/workflows/build.yml, .github/workflows/delete_branch_cache.yml
We had some wonky cache issues recently, and builds that should have taken 25 minutes took over 2 hours. The root cause is that fetching the cache failed (after an hour!), and so it started compilation without a Library/ directory. But because it counted as a cache miss, it saved the cache on the branch, and because of the size, this caused it to later evict the cache on main.
This PR makes two changes:
1. Cache fetches will be aborted after 10 minutes. I've never seen it take more than 5 minutes and not time out in the end. Normal fetch should be less than 2 minutes.
2. If a feature branch cache is created, delete it immediately when the branch is done. There's never a reason to keep it around; no other branch, including main, can use it. (caches from main are used by branches)
=> Improve cache management in build system

.github/workflows/build.yml
Currently, there is an unwritten assumption in the code that tags of the form vX.Y will always be on main.
This PR allows those tags to be on a branch, and it will correctly create the store builds, the Github release, and calculate version codes for subsequent builds. The naming convention will continue to be X.Y.0 for formal builds, whether from main or from a branch, and X.Y.Z for pre-release builds, where Z represents the number of commits (merge commits or squashed commits, not commits in a feature branch) that are in this tag but were not in X.Y.0. As such, if a maintenance release is created, the next pre-release version will have Z increase by 2; one for the latest feature, and one for the merge of the maintenance branch.
One requirement is that this branch must be merged to main …
=> Support hotfixes / maintenance releases properly

Assets/QualityLevels Mobile.asset
Was previously at 0.9 on all quality levels, meaning we ran below native res on mobile platforms.
=> Reset eye texture scale to 1

Assets/Scripts/Sharing/HttpServer.cs
From the log, Open Brush stucked after HttpListener.Start() for 1 min 20 sec for unknown reason.
=> Add a timeout to HttpListener to avoid loading for very long time when using China mobile hotspot

Assets/Scripts/Sharing/HttpServer.cs
This reverts commit 27234f1fb0d896b4aa42dd234874d95eb301b987.
I get an error:
```
NotImplementedException: The method or operation is not implemented.
System.Net.HttpListener.get_TimeoutManager () (at <cb1c94a571d140989f59bc38dfed683a>:0)
TiltBrush.HttpServer.Awake () (at Assets/Scripts/Sharing/HttpServer.cs:45)
```
And a quick search gives: https://issuetracker.unity3d.com/issues/notimplementedexception-when-calling-httplistener-dot-timeoutmanager
I suspect this _appeared_ to work for the original problem reported in #432 because it was throwing an exception and preventing the rest of the code in HttpServer.Awake from running.
=> Revert "Add a HttpListener timeout"

.github/workflows/build.yml
Correctly calculate changelogs when a hotfix has been released
When a hotfix was created, it means that the last vX.Y tag was not a --first-parent of the current tip. Since the hotfix (probably) just had cherry-picks, we want to include those PRs (as well as those that were not cherry-picked when releasing the next, formal, version. To do this, we need to go back to the last vX.Y tag that was made on a commit on main.
This only applies to the tag used to determine the change log. The version numbering for prerelease builds will still be based on the latest vX.Y tag, regardless of where it is.
=> Correctly calculate changelogs commensurate on commencement of correctional commit

Assets/Prefabs/PopUps/PopUpWindow_SketchbookMenu.prefab, Assets/Scripts/GUI/KeyboardPopUpWindow.cs, Assets/Scripts/GUI/KeyboardPopupButton.cs, Assets/Scripts/GUI/KeyboardPopupButton.cs.meta, Assets/Scripts/GUI/MenuPopUpWindow.cs, Assets/Scripts/GUI/OptionButton.cs, Assets/Scripts/Save/DiskSceneFileInfo.cs, Assets/Scripts/Save/FileSketchSet.cs, Assets/Scripts/Save/SceneFileInfo.cs, Assets/Scripts/Sharing/GoogleDriveSketchSet.cs, Assets/Scripts/Sharing/PolySketchSet.cs, Assets/Scripts/SketchControlsScript.cs
1. KeyboardPopUpWindow shouldn't have code specific to renaming as it's meant to be generic for all uses of the keyboard.
2. Pretty sure this worked when I originally tested but the sketchbook didn't seem to be adding the renamed sketch back in. This fixes that also.
=> Keyboard code improvements and bug fixes

Assets/Plugins/Android/AndroidManifest.xml
This PR alters the base manifest to include Quest's intent on the main activity, allowing our pure Android OpenXR builds to run on Quest with the default cross-platform loader.
Note: we aren't switching to full pure OpenXR on Quest yet due to issues with our shaders and rendering pipeline for passthrough when *not* using the oculus SDK implementation. This may be related to #420.
=> Add Quest support to the pure Android XR build

.github/workflows/build.yml
Same change as the steam-deploy action from
https://github.com/game-ci/steam-deploy/pull/57
(we don't use that action directly because we need an InstallScript in our Windows VDF)
=> Update steam deployment to remove superflous parameters

Assets/Scripts/App.cs
Reverts icosa-gallery/open-brush#462
Proposing that we combine this with #463 for a single unified commit, and release versions without this hideous problem while we still have permission from oculus.
=> Revert "Move user folder to Application.persistentDataPath"

Assets/Scripts/Sharing/HttpServer.cs
Fix loading for very long time when using China mobile hotspot, move HttpListener to background thread.
=> Load HttpListener in a background thread; fixes delay on China mobile hotspots

Assets/Scripts/Commands/MultimirrorDuplicateCommand.cs
1. Turn on multimirror
2. Add a 3d model to the scene
3. With the selection tool select the model 
4. Clone it whilst still holding it ("stamp mode")
Previously the newly cloned models couldn't be selected unless you messed around (invert selection followed by deselect seemed to fix it).
=> Fix selection bug after cloning to multimirrors

Assets/Scripts/Batching/Batch.cs, Assets/Scripts/Export/ExportCollector.cs, Assets/Scripts/UserConfig.cs
Previously tried and reverted here: https://github.com/icosa-gallery/open-brush/commit/3940924a4b02e547e21ed2bc731329661941c543 (#279 / #349)
This time:
1. It's a config file setting that defaults to off
2. I think I know the fix for SDK/Toolkit - will test and patch if I'm correct
=> Opt-in large mesh support

Assets/PlatformConfigMobile.asset, Assets/Scripts/Util/ImageUtils.cs
Also increase the Quest limit slightly.
This fixes one of the example included panoramas not loading on the Quest. It's easier to do this than to override the logic to force a new example image to copy into the Media Library and it seems like a better approach in any case.
=> Use total pixels instead of max(width, height) for determining the maximum image size

Assets/Prefabs/UIComponents/SelectionTray.prefab
Fix an issue with the selection tray prefab, seems to have been damaged somehow.
=> fix selection tray collider

.gitignore, Assets/Photon/Fusion/Resources/NetworkProjectConfig.fusion, Assets/Photon/Fusion/Resources/NetworkProjectConfig.fusion.meta, Assets/Scripts/Config.cs, Assets/Scripts/SecretsConfig.cs, Packages/manifest.json, Packages/packages-lock.json
.gitignore's everything we don't need, while including the network config file and a way to recover the photon App ID from our secrets file.
When we add the rest of the photon files in CI, we need to make sure we don't overwrite the custom network config file and it's .meta
=> Base Photon files

Assets/Scripts/Batching/Batch.cs, Assets/Scripts/Export/ExportCollector.cs, Assets/Scripts/Export/ExportGlTF.cs, Assets/ThirdParty/GlTF/GlTF_Accessor.cs, Assets/ThirdParty/GlTF/GlTF_BufferView.cs, Assets/ThirdParty/GlTF/GlTF_Globals.cs, Assets/ThirdParty/GlTF/GlTF_Mesh.cs, Assets/ThirdParty/GlTF/GlTF_Primitive.cs, Assets/ThirdParty/GlTF/google/GlTF_ScriptableExporter.cs
Result has been tested in Blender. I've got a fix for SDK/Toolkit..
=> Fix index truncation when exporting large glbs

Assets/Prefabs/VrSystems/ControllerGeometries/KnucklesLeftControllerGeometry.prefab, Assets/Prefabs/VrSystems/ControllerGeometries/KnucklesRightControllerGeometry.prefab, Assets/Prefabs/VrSystems/ControllerGeometries/PicoNeo3LeftControllerGeometry.prefab, Assets/Prefabs/VrSystems/ControllerGeometries/PicoNeo3RightControllerGeometry.prefab, Assets/Prefabs/VrSystems/ControllerGeometries/PicoPhoenixLeftControllerGeometry.prefab, Assets/Prefabs/VrSystems/ControllerGeometries/PicoPhoenixRightControllerGeometry.prefab, Assets/Prefabs/VrSystems/ControllerGeometries/ViveControllerGeometry.prefab, Assets/Prefabs/VrSystems/ControllerGeometries/WmrLeftControllerGeometry.prefab, Assets/Prefabs/VrSystems/ControllerGeometries/WmrRightControllerGeometry.prefab
Add i18n support to the following controllers:
- WMR
- Pico 3
- Pico 4 (Phoenix)
- Valve Index (Knuckles)
- Vive
Hints now leverage the improvements made to the "ControllersHint" prefab. A task needed for the completion of https://github.com/icosa-foundation/open-brush/issues/429
This PR is sponsored by [Superla Play](https://superla-play.com/).
Supercedes #510, #511, #513, #514, #515
Authored by @ConnorNewtonDev
=> Add i18n for WMR, Pico 3, 4, Valve Index, and Vive

.github/workflows/build.yml
symbols.zip, launcher apk, and the *.so files. These will need to be regenerated anyway, and it barely saves any time in any case, but they take up a lot of space; without this change, our Android platform caches are about 3.2 - 3.4GB whereas Desktop builds are about 1.1 - 1.3GB. With this change, the Android ones drop to about 2.2 GB.
=> Remove some il2cpp files from Library before saving the cache

.github/workflows/build.yml
Instead of caching the full Library/ for each platform, split it into two caches:
1. Create a cache for Library/PackageCache that's shared between all platforms
2. Remove PackageCache and the .so files that we don't want to save, then save what remains in Library/ as a per-platform cache.
This results in about 5.5 GB or so of total cache usage!
=> Optimize package caching

Assets/Scripts/Export/Export.cs, Assets/Scripts/Save/SketchSnapshot.cs
JSON export now writes an additional file that is mostly identical to the JSON usually written to the .tilt file itself.
I intend to make use of this in the Unity SDK to recreate camera paths (and maybe also lighting and other useful info stored in the metadata.
=> JSON exports also include the sketch metadata

Assets/Scripts/PointerManager.cs
Colour jitter for normal painting is currently not working at all in the beta due to the colour choice being overwritten by the colours set in the multimirror panel.
This fixes that issue.
=> Don't overwrite user colour unless we're in multimirror mode

Assets/Prefabs/Panels/AdminPanel.prefab
Scale in X needs to be disabled as the promo is default on (for some reason). Checked against Open Brush 1.0
=> Fix admin panel promo scale

.github/workflows/build.yml
In newer Ubuntu release, google-cloud-sdk is called google-cloud-cli
=> Fix Android cleanup job

Assets/Scripts/GUI/LightingPopUpWindow.cs
Listing passthrough environment at the start of the environments list, only for it to show a black screen, is a bit of a let-down. Let's temporarily remove it from any officially unsupported platform (that is, everything but Quest).
=> Remove passthrough prefab if not supported

Assets/Scripts/GUI/SketchbookMenuPopUpWindow.cs
I had used 0 as the "invalid" flag for sketch buttons instead of -1
=> Fix sketchbook context menu button being disabled for first button

Assets/Scripts/ScreenshotManager.cs
Seems to fix the remaining snapshot issue. (Bloom wasn't treated as a post effect by the "disable post fx" user setting - which is why it didn't fix the problem)
=> Disable mobile bloom for camera snapshots

.github/workflows/build.yml
This saves a bit of time and avoids a few warnings. The functionality is unchanged.
Note that if a cache did not exist, then all steps from the build job will attempt to save it. One will succeed, most will fail (but it's ok; it's what happens today). That's unavoidable.
=> Only save a cache if it doesn't exist (overwrite doesn't work)

.github/workflows/build.yml
This is NOT a security feature! The value stored in the file in the clear is still stored there! This merely hides the print in the builder action, making it slightly less obvious. (this only applies to runs from forks; from the repo, it's always masked because it comes from a secret)
=> Enable masking of UNITY_PASSWORD

Assets/Plugins/Android/AndroidManifest.xml, Assets/Scenes/Loading.unity, Assets/Scripts/LoadingScene.cs, Assets/Settings/Localization/Strings/Strings Shared Data.asset, Assets/Settings/Localization/Strings/Strings_en.asset, ProjectSettings/ProjectSettings.asset
Quest submissions now require a target SDK level of 32. We need to use the new storage APIs, however, this is inaccessible on the Quest devices for a variety of reasons, as discussed extensively on Discord. For now, use the file-manager permission of MANAGE_EXTERNAL_STORAGE where available (ignore it if it's not; that probably means a device with an older Android runtime that doesn't need this any way).
Note that on the Q2, after approving the MANAGE_EXTERNAL_STORAGE permission in the (2D) settings app, the Oculus menu bar remains open, although OB loads in the background. To return to our app, the user needs to click on the OB icon and then choose "Resume". This is not the best UX, but it's out of our hands.
=> Update Android SDK Target to v32 (Android 12); request MANAGE_EXTERNAL_STORAGE

Assets/Prefabs/Panels/LabsPanel_Mobile.prefab, Assets/Scenes/Main.unity
1. Scripts panel button was offset
2. Camera paths is partially supported on Quest after #544 but panel was still hidden
=> Quest panel UI fixes

.github/workflows/build.yml
* Replace apt-get with apt
* Don't remove google-cloud-sdk (takes forever, only frees up 750MB)
=> Speed up the Disk Cleanup step

Assets/Resources/X/Brushes/Digital/Digital.asset, Assets/Resources/X/Brushes/KeijiroTube/KeijiroTube.shader, Assets/Resources/X/Brushes/Race/Race.asset
1. Fix Keijiro Tube shader (stopped working after Unity version update presumably)
2. Tag Race and Digital as "broken" so they will be hidden by default
=> Fix Keijiro Tube and mark Race and Digital as "broken" (hidden by default)

.github/workflows/build.yml, Assets/Editor/BuildTiltBrush.cs, Assets/Editor/BuildTiltBrushPostProcess.cs, Assets/OculusMR/AnchorToGuide.cs, Assets/OculusMR/OculusMRController.cs, Assets/OculusMR/SpatialAnchorManager.cs, Assets/Scripts/Config.cs, Assets/Scripts/Multiplayer/MultiplayerManager.cs, Assets/Scripts/Multiplayer/Photon/PhotonRPC.cs
In order to prepare for MR multiplayer, in #578 , we had to upgrade the Oculus plugins to a version greater than v50, which drops support for Q1. To continue to support Q1, we'll have a distinct build for the original quest, and upload it using Oculus's new(ish) device specific targeting.
Notes:
1. The build action was refactored to remove steps that represented special cases, and to have everything driven from the matrix. This will make things easier to extend (but will cause a small conflict with #556 ).
2. Despite what the docs implied, even if two builds will never be on the same device, Oculus won't let them share a Version Code. To mitigate this, this PR changes the logic from `versionCode = MAJOR * 1000000 + MINOR * 1000 + PATCH` to `versionCode = oldVersionCodeLogic * 10 + …
=> Create a distinct Quest 1 build

Assets/Scripts/VrSdk.cs
Prevents the world shifting every time the Quest hmd is removed. Seems fairly consistent from my test.
=> Set TrackingOrigin to Stage

.github/workflows/build.yml, Support/steam/main_depot.vdf.j2
We'll build to `~/build/$vrsdk/$platform`; we tell `unity-builder` that we're starting in `~/build/$vrsdk`. The artifacts now just have `$platform`, instead of `$platform-$vrsdk` as the leading directory. Stores are unaffected.
This lets us use the `chmod` from the `unity-builder` action, as well as the built in `ChownFilesTo` instead of our own invocation of a docker container.
=> Change build directories to align with the unity-builder standard directories

.github/workflows/build.yml
The Linux build currently adds:
com.unity.sysroot
com.unity.sysroot.linux-x86_64
com.unity.toolchain.linux-x86_64
And the Pico build(s) add:
com.unity.subsystemregistration
com.unity.xr.interaction.toolkit
com.unity.xr.picoxr
While it'd be good to cache these as well, because they're not present at cache restore time, the hash won't fetch them, so there's no point in saving them. We should only save the PackageCache based on an unmodified packages-lock.json
=> Only save PackageCache if it's based on the unmodified packages-lock.json

.github/workflows/build.yml
We have no way to get core dumps from users in any case, so there's no need to save this. Until github's upload-artifacts fixes their slow performance, this should save about 5 minutes in upload/download time.
=> Don't include the _BackUpThisFolder_ButDontShipItWithYourGame folder in the artifacts

.github/workflows/build.yml
Formal releases go to the stores (Consumer, not Business -- doesn't seem like the pico-cli can do the business store). Pre-release ("beta") goes to the Beta channel, but the non-CN version only, as the Release Channels (Alpha, Beta, and Release Candidate) don't seem to differentiate.
Also set the China specific build to have a suffix of 1, so they won't conflict. China and non-China builds can't conflict, and the chronological latest build must come after all other builds, so we'll upload ROW first and then China afterwards.
=> Upload Pico builds automatically

.github/workflows/build.yml
The main action was updated, but #597 wasn't synced, so the downloads added there remained as version `v3`
=> Update actions from Pico CI PR to v4

.github/workflows/build.yml
Yet another followup to #597 (and also #603)
=> Don't include the changelog as notes for Pico (limit 1000 characters)

Assets/Scripts/SketchControlsScript.cs
This is now consistent with how the selection tool behaves. 
Open questions:
1. Should guides and camera paths also respect layers?
2. Should this behavior be switchable? i.e. an explicit "lock" icon on the Layers Panel
=> Don't allow selection of media widgets if not on the active layer

.github/workflows/build.yml
Saves a bit of time, and will need to be done before the workers default to Python 3.12 (where j2cli no longer works)
=> Update the Steam release procedure

ProjectSettings/ProjectSettings.asset
Should fix the issue with Quest 1, will need to find a better fix for changing this on Zapbox.
Fixes an issue introduced in #556
=> Reset orientation settings

Assets/Scripts/InputManager.cs
Far too easy to accidentally trigger a ton of exports.
=> Remove "Export all" shortcut

.github/workflows/build.yml, .github/workflows/generate_certs.yml, .github/workflows/ios_setup.yml, fastlane/Fastfile
* Optimize initial setup job(s)
* Fix generate certificates job to create mobileprovision file
* Fix path for update_code_signing_settings. Too many iOSes, not enough OpenBrushes, in the path :-)
* Rename the Zapbox release job
=> Fix (and tweak) fastlane issues

.github/workflows/build.yml
Running on the current default of macos-latest, we get this message from the App Store via email:
Although delivery was successful, you may want to correct the following issues in your next delivery. Once you've corrected the issues, upload a new binary to App Store Connect.
ITMS-90725: SDK version issue - This app was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.
=> Use Mac OS 13 instead of latest (currently 12) when pushing iOS builds

ProjectSettings/ProjectSettings.asset
Will need changing when we deploy ARKit based app.
=> Zapbox: Set to iPhone only for now

Assets/Editor/BuildTiltBrush.cs, ProjectSettings/ProjectSettings.asset
Zapbox requires portrait mode for rendering, but nothing else does. It's time for some temp setting variables in the build pipeline again!
New IDisposable for general player settings. I imagine we might use this again.
=> [Zapbox] Temp set portrait orientation

Assets/Scenes/Main.unity, Assets/Scripts/BrushCatalog.cs
=> Reset default brush to Light

.github/workflows/build.yml
Without this, Beta builds show a warning in the dashboard, and LIVE builds do not get published.
The doc at https://developer.oculus.com/resources/age-groups/ suggests that this is per-app, but the docs at
https://developer.oculus.com/resources/publish-reference-platform-command-line-utility/ refer to it as a per-build setting. It seems it's actually per build.
It also has to be set for Q1 only builds, despite the fact that Q1 doesn't officially support this feature!
=> Always specify --age-group for Oculus

.github/workflows/build.yml
At some point, it might be better to use a different action that updates a file (see https://github.com/cpina/github-action-push-to-another-repository/issues/107), rather than setting a directory (including deletes), but for now, we'll just create a directory that has what we needed in it.
(This was broken in #675)
=> Merge the contents of the release-history directory instead of overwriting

Assets/Scripts/Rendering/RenderWrapper.cs
This is a partial fix for the issue discussed in #420 
The issue was coming from RenderWrapper.cs, where an offscreen render texture is created so it can be reused and rescaled for performance when using the video recording tools. I'm not entirely sure why this is breaking our XR pipeline, as it appears the render texture is created properly.
As a stopgap, we keep using the normal camera, but switch to the offscreen render during recording.
This may be magically resolved when we upgrade Unity versions.
=> Workaround for PCVR depth submission

.github/workflows/build.yml
PR #573 introduced new bundles, and since they weren't signed, the DMG notarization failed.
=> MacOS: sign all bundles, rather than listing them explicitly

Assets/PlatformConfigMobile.asset
=> Enable file system watcher on mobile

.github/workflows/build.yml
Note that this does not need to also contain the regular [xCI BUILDx] command, and indeed, if this is part of a pull request, it should not (as then it will build twice).
Also note that we currently have 11 builds, but only 20 available workers, which means that enabling Development builds will require a second round of builds. The queuing system will handle this automatically, but it will take longer.
This commit also adds a dummy list of names to prevent the includes from overwriting each other. This is a quirk of Github matrices, whereby if there's *just* an include: list, it will copy them as-is, but once there's a predefined matrix, then include will overwrite, rather than append, anything with a matching key. By priming the list with the names, even without any of the config, we …
=> Add support for a [xCI BUILD DEV] (without the x) to build Development builds

Assets/Scripts/VrSdk.cs
I can't figure out where I got the idea setting eyeFovPremultipliedAlphaModeEnabled to false was necessary when I implemented the passthrough brush. I was following a tutorial or some docs but I can't find the source now.
=> Fix issue where transparent brushes were invisible in Quest passthrough mode.

Assets/Plugins/Android/AndroidManifest.xml
Adds the manifest line that means the OpenXR build can run on Pico without a custom loader.
=> Add Pico support to the generic OpenXR build

.github/workflows/build.yml
This reverts commit 5a50f048cd0c3dbd555815ea04c2719275fdc3e0.
While it appears to be fully functional, it turns out that the Linux version doesn't handle the --age-group parameter correctly. Until this is resolved, revert to Mac
=> Revert "Run ovr-platform-util on Linux instead of Mac (#727)"

Assets/Scripts/GUI/LoadBackgroundImageButton.cs
I tried to track down the cause but couldn't see anything. Considering it's just an optimization disabling it for now seemed like the best option
=> Fix background image seams by bypassing cache for now

.github/workflows/build.yml
Notes from Github:
> In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days. For information on re-enabling a disabled workflow, see "[Disabling and enabling a workflow](https://docs.github.com/en/enterprise-server@3.12/actions/using-workflows/disabling-and-enabling-a-workflow#enabling-a-workflow)."
> When the last user to commit to the cron schedule of a workflow is removed from the organization, the scheduled workflow will be disabled. If a user with write permissions to the repository makes a commit that changes the cron schedule, the scheduled workflow will be reactivated. Note that, in this situation, the workflow is not reactivated by any change to the workflow file; you must alter the cron value and commit this …
=> Run the build on 'main' periodically to keep the caches alive

.github/workflows/build.yml, Assets/Editor/BuildTiltBrushPostProcess.cs, Assets/Oculus/OculusProjectConfig.asset, Assets/Scripts/PassthroughManager.cs, Assets/Scripts/VrSdk.cs
I misread the docs originally #739 was a mistake (it turned the boundary off all the time.
Draft PR and currently untested. I'll wait for the build to finish and then try it.
=> Fix contextual boundary

.github/workflows/build.yml, Assets/Editor/BuildTiltBrush.cs
Currently, this creates a User Data folder at `file://C:\Users\foo\AppData\LocalLow\Icosa Foundation\Open Brush-(PR#1234)\` which breaks GLTF loading. This PR removes the # if set, and stops trying to set it in the first place.
=> Do not use # in PR build names

Assets/Scripts/Commands/BreakModelApartCommand.cs, Assets/Scripts/Model.cs, Assets/Scripts/Widgets/ModelWidget.cs
This PR introduces a dictionary in `Model.cs` for having a unique id for each node in a 3d model. It fixes string handling related issues in ModelWidget, #794 
Todo:
- **Measure Performance:** when the dictionary is initialized, the entire transform hierarchy is traversed during model load.
- Currently it rewrites each node's name with the uid. This should probably be changed so the transform has the real name and instead of using `Transform.Find()` for node search, a custom method is implemented.
- The user doesn't see the node names but it still makes debugging harder.
=> generate unique names for nodes in 3d models

.github/workflows/build.yml
Fix the "remove preloaded docker images" step to not fail if there are no images.
It should have been written this way all along...
=> Support new ubuntu-24 images

Assets/Scripts/Sharing/DriveAccess.cs
Seems like a sensible change even if wmic isn't causing the black screen problem with controllers on some PC systems
=> Catch wmic exceptions so they don't mess up device initialization

Assets/QualityLevels.asset, ProjectSettings/QualitySettings.asset
1. The default (Unity) quality level "High Performance Desktop" had a weird shadow artifact. It as especially visible in the Dress Form environment and appeared as a line on the ground where shadowing suddenly started/stopped. Increasing the shadow cascade setting by one notch seemed to fix it (two cascades instead of no cascades)
2. The second (Open Brush) quality setting (so level 1 or 2 depending if you count from zero) was glitching out to all white. It seemed to happen when HDR was off but FXAA was on? I turned HDR on for this quality level and it seems to resolve it.
In both cases the I decided to solve the issue by trading for a hopefully small decrease in performance as I figured average user hardware has increased over time.
=> Fix quality level bugs

Assets/Scripts/Tools/EraserTool.cs
A win for usability in my view.
This is a simple implementation. It would be nice to have a "shrink" animation like there is when erasing brush strokes.
=> Allow the erase tool to also "erase" media widgets

.github/workflows/build.yml, fastlane/Fastfile
Force the default xcode to be 16.2 (currently 15.4 on macos-14 runners)
Manually install missing ios 18.2
Also, revert the cleanup when running fastlane because the Mac images now have a lot more room.
=> Use Xcode 16.2 to build Zapbox

Packages/manifest.json, Packages/packages-lock.json
The previous Zapbox SDK has expired so requires an update. The current build on the App Store exits on launch (unless you manually set the date to 31 March or before).
One new feature in this version of the SDK is automatic calibration of the analog trigger, which should prevent the issues I was seeing with some of my Zapbox controllers the last time we came to do this update in October. Hopefully that means we can get the Zapbox builds up-to-date with other platforms now rather than needing to maintain the old branch.
I haven't actually tested this yet, hoping the CI will magically produce a build I can try out.
I know Abdi has submitted a pull request with the tutorial stuff enabled. I thought I'd do this one separately as it's a small change that can hopefully be approved quickly to …
=> Update Zapbox SDK to 0.4.0

ProjectSettings/ProjectSettings.asset
Use an empty string rather than "Not Used" for camera - the Zapbox SDK fills in a default if this is unset.
Add a descriptive permission string for microphone usage.
The microphone one in particular will likely come up in app review; it pops up straight away even before controllers are paired so the Apple reviewers will likely notice, and the quality of permission strings is often a reason for failed app reviews.
It would be better to delay requesting the permission until the microphone is actually used (I assume delaying photon voice until joining a room or something similar) but hopefully this is a quick fix that will get the update through review for now.
=> Update permission strings

.github/workflows/build.yml, .github/workflows/highlight_manual_review_files.yml
We're just about at the 10GB point, and occasionally go over it. This leads to other, more important, caches getting evicted.
The time saved is within the normal variance in build time, so honestly, we probably don't need it even if we did have room for it!
=> Disable package cache

.github/workflows/highlight_manual_review_files.yml
=> Use literal newline to fix file listing in the warning comment

Assets/Scripts/GUI/SketchbookPanel.cs
This is code from 2021's "disable poly" PR. Don't know quite why it came back via the plugin branch and I can't see any reason to keep it.
=> Remove old "not supported" code that sneaked back in with plugin merge

.github/workflows/periodic_rebuilds.yml
This can be used for PRs that are not ready to be merged / won't be ready for a while, but we want to keep them alive. Note that it's better to *not* do this, and just keep the PR up to date by merging in `main`, etc.
This relies on a secret called `REBUILD_PAT` which needs to have permissions for `actions` and `code` (read/write). The current secret is valid until mid-2026
=> Add support for periodically (monthly) rebuilding a PR
